version: "3.9"
services:

  # database:
  #   build: ./backend
  #   # container_name: photo-album-gen-database
  #   command: [ "--app", "flaskr", "init-db" ]

  backend:
    build: backend/.
    volumes:
      - ./backend:/app
    environment:
      FLASK_DEBUG: "true"
    networks:
      - backend_nw
    depends_on:
      # - database
      - cache

  frontend:
    build: frontend/aespa/
    volumes:
      - ./frontend/aespa/:/app
    ports:
      - "4200:80"
    networks:
      - frontend_nw

  cache:
    image: "redis:alpine"
    networks:
      - backend_nw

  loadbalancer:
    image: nginx:latest
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "5000:4000"
    networks:
      - backend_nw

networks:
  frontend_nw:
  backend_nw:
